import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Blog App | Signup',
    description: 'Generated by create next app',
};

export default function SignupLayout({ children }: { children: React.ReactNode }) {
    return <>{children}</>;
}
